<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>user_gateway.BLL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="CloudinaryDotNet" Version="1.27.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\user-gateway.DAL\user-gateway.DAL.csproj" />
    <ProjectReference Include="..\user-gateway.Domain\user-gateway.Domain.csproj" />
  </ItemGroup>

</Project>
